#!/usr/bin/env bash
# Default OpenCV build components
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_SHARED_LIBS=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_opencv_apps=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_opencv_js=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_ANDROID_PROJECTS=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_DOCS=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_EXAMPLES=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_PACKAGE=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_TESTS=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_PERF_TESTS=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_WITH_DEBUG_INFO=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_WITH_DYNAMIC_IPP=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_FAT_JAVA_LIB=ON"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_ANDROID_SERVICE=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_CUDA_STUBS=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DBUILD_JAVA=ON"
# install default all is OFF
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DINSTALL_TESTS=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DINSTALL_C_EXAMPLES=OFF"
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DINSTALL_ANDROID_EXAMPLES=OFF"
# OpenCV build options
export COMMON_CV_CFG_FLAGS="$COMMON_CV_CFG_FLAGS -DCV_TRACE=ON"
